[ALPS08325329] use realpath
commit 392ceb5 ("kleaf: make rel_path emit an error")
causes following build error

ERROR: rel_path is deprecated. For Kleaf builds, use realpath kernel_device_modules-6.1 --relative-to kernel-6.1 instead.
Target //kernel_device_modules-6.1:mgk_64_k61_internal_modules_install.userdebug failed to build

MTK-Commit-Id: d1e2f12b453027c0786e15e2707631ffe55b4780

CR-Id: ALPS08325329
Feature: Kernel SI Operation
Change-Id: Ia813e7fad54be78ee383db4a308affd7cbb1caa0